# Generated by Django 5.2.9 on 2026-01-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='languages',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
